"""test_coerenza

Revision ID: 3255dc562a37
Revises: 8d0ef4207d3e
Create Date: 2026-07-18 12:33:49.483051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3255dc562a37'
down_revision: Union[str, None] = '8d0ef4207d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rate_limit')
    op.alter_column('emails_emaildata', 'image_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('emails_emaildata', 'image_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('emails_emaildata', 'status_int',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('emails_emaildata_image_id_key', 'emails_emaildata', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('emails_emaildata_image_id_key', 'emails_emaildata', ['image_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('emails_emaildata', 'status_int',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('emails_emaildata', 'image_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('emails_emaildata', 'image_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table('user_rate_limit',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_banned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ban_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('banned_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_rate_limit_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='user_rate_limit_pkey')
    )
    # ### end Alembic commands ###
