"""reset

Revision ID: dc70cec88e99
Revises: 
Create Date: 2026-06-17 21:43:11.515718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc70cec88e99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rate_limit')
    op.alter_column('emails_emaildata', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('emails_emaildata', 'latitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('emails_emaildata', 'longitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('emails_emaildata', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('emails_emaildata', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('emails_emaildata', 'image_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('emails_emaildata', 'image_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('emails_emaildata', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('emails_emaildata', 'image_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('emails_emaildata_image_id_67d43c66_like', table_name='emails_emaildata')
    op.drop_constraint('emails_emaildata_image_id_67d43c66_uniq', 'emails_emaildata', type_='unique')
    op.drop_index('emails_emaildata_status_int_cc4dddc8', table_name='emails_emaildata')
    op.drop_index('emails_emaildata_user_id_5d31218d', table_name='emails_emaildata')
    op.create_index(op.f('ix_emails_emaildata_id'), 'emails_emaildata', ['id'], unique=False)
    op.create_foreign_key(None, 'emails_emaildata', 'users', ['user_id'], ['id'])
    op.drop_column('emails_emaildata', 'status_int')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'can_regenerate_key',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_users_api_key', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_constraint('users_facebook_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_facebook_id'), 'users', ['facebook_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_facebook_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_facebook_id_key', 'users', ['facebook_id'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_api_key', 'users', ['api_key'], unique=True)
    op.alter_column('users', 'can_regenerate_key',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('emails_emaildata', sa.Column('status_int', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'emails_emaildata', type_='foreignkey')
    op.drop_index(op.f('ix_emails_emaildata_id'), table_name='emails_emaildata')
    op.create_index('emails_emaildata_user_id_5d31218d', 'emails_emaildata', ['user_id'], unique=False)
    op.create_index('emails_emaildata_status_int_cc4dddc8', 'emails_emaildata', ['status_int'], unique=False)
    op.create_unique_constraint('emails_emaildata_image_id_67d43c66_uniq', 'emails_emaildata', ['image_id'], postgresql_nulls_not_distinct=False)
    op.create_index('emails_emaildata_image_id_67d43c66_like', 'emails_emaildata', ['image_id'], unique=False)
    op.alter_column('emails_emaildata', 'image_file',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('emails_emaildata', 'image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('emails_emaildata', 'image_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('emails_emaildata', 'image_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('emails_emaildata', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('emails_emaildata', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('emails_emaildata', 'longitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('emails_emaildata', 'latitude',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('emails_emaildata', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('user_rate_limit',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_banned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ban_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('banned_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_rate_limit_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='user_rate_limit_pkey')
    )
    # ### end Alembic commands ###
